# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grantaDiagram.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1059, 664)
        Form.setStyleSheet("QMenuBar {\n"
                           "background-color: rgb(250, 234, 153);\n"
                           "font: 87 10pt \"Arial Black\";\n"
                           "padding-left: 3px;\n"
                           "    color: rgb(82, 30, 1);\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item {\n"
                           "spacing: 3px; /* spacing between menu bar items */\n"
                           "padding: 1px 4px;\n"
                           "background: transparent;\n"
                           "border-radius: 4px;\n"
                           "background-color: rgb(250, 234, 153);\n"
                           "}\n"
                           "\n"
                           "QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
                           "background: #fac983;\n"
                           "}\n"
                           "\n"
                           "QMenu {\n"
                           "background-color: rgb(149, 166, 174); \n"
                           "    font: 75 8pt \"Arial Black\";\n"
                           "}\n"
                           "\n"
                           "QMenu::item {\n"
                           "background-color: transparent;\n"
                           "}\n"
                           "\n"
                           "QMenu::item:selected {\n"
                           "background-color: #fac983; /* rot */\n"
                           "}\n"
                           "QWidget{background-color: rgb(255, 253, 223);}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1042, 630))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout.addWidget(self.label_32)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setObjectName("label_31")
        self.verticalLayout.addWidget(self.label_31)
        self.gantaDiagramDataWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gantaDiagramDataWidget.sizePolicy().hasHeightForWidth())
        self.gantaDiagramDataWidget.setSizePolicy(sizePolicy)
        self.gantaDiagramDataWidget.setMinimumSize(QtCore.QSize(1024, 574))
        self.gantaDiagramDataWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gantaDiagramDataWidget.setObjectName("gantaDiagramDataWidget")
        self.line = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line.setGeometry(QtCore.QRect(50, 0, 21, 621))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_2.setGeometry(QtCore.QRect(90, 0, 21, 621))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_3.setGeometry(QtCore.QRect(130, 0, 21, 621))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_4.setGeometry(QtCore.QRect(250, -10, 21, 621))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_5.setGeometry(QtCore.QRect(210, -10, 21, 621))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_6.setGeometry(QtCore.QRect(170, -10, 21, 621))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label.setGeometry(QtCore.QRect(60, 100, 131, 20))
        self.label.setStyleSheet("background-color: rgb(255, 0, 4);\n"
                                 "\n"
                                 "border: 1px solid rgb(255, 0, 4);\n"
                                 "border-radius: 10px;\n"
                                 "")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 141, 20))
        self.label_2.setStyleSheet("background-color: rgb(200, 100, 4);\n"
                                   "\n"
                                   "border: 1px solid rgb(200, 100, 4);\n"
                                   "border-radius: 10px;\n"
                                   "")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.line_7 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_7.setGeometry(QtCore.QRect(370, -10, 21, 621))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_8.setGeometry(QtCore.QRect(490, 0, 21, 621))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_9.setGeometry(QtCore.QRect(450, 0, 21, 621))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_10.setGeometry(QtCore.QRect(410, 0, 21, 621))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_11.setGeometry(QtCore.QRect(330, -10, 21, 621))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_12.setGeometry(QtCore.QRect(290, -10, 21, 621))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.label_3 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_3.setGeometry(QtCore.QRect(240, 160, 181, 20))
        self.label_3.setStyleSheet("background-color: rgb(20, 20, 200);\n"
                                   "\n"
                                   "border: 1px solid rgb(20, 20, 200);\n"
                                   "border-radius: 10px;\n"
                                   "")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_4.setGeometry(QtCore.QRect(200, 100, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_5.setGeometry(QtCore.QRect(240, 130, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_6.setGeometry(QtCore.QRect(430, 160, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_7.setGeometry(QtCore.QRect(140, 200, 41, 20))
        self.label_7.setStyleSheet("background-color: rgb(20, 200, 200);\n"
                                   "\n"
                                   "border: 1px solid rgb(20, 200, 200);\n"
                                   "border-radius: 10px;\n"
                                   "")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_8.setGeometry(QtCore.QRect(190, 200, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_9.setGeometry(QtCore.QRect(60, 240, 441, 20))
        self.label_9.setStyleSheet("background-color: rgb(20, 255, 0);\n"
                                   "\n"
                                   "border: 1px solid rgb(20, 255, 0);\n"
                                   "border-radius: 10px;\n"
                                   "")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.gantaDiagramDataWidget)
        self.label_10.setGeometry(QtCore.QRect(510, 240, 101, 16))
        self.label_10.setObjectName("label_10")
        self.line_37 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_37.setGeometry(QtCore.QRect(610, 0, 21, 621))
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_38.setGeometry(QtCore.QRect(730, -10, 21, 621))
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.line_39 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_39.setGeometry(QtCore.QRect(850, -10, 21, 621))
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.line_40 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_40.setGeometry(QtCore.QRect(690, -10, 21, 621))
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.line_41 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_41.setGeometry(QtCore.QRect(770, -10, 21, 621))
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.line_42 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_42.setGeometry(QtCore.QRect(890, 0, 21, 621))
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.line_43 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_43.setGeometry(QtCore.QRect(650, -10, 21, 621))
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.line_44 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_44.setGeometry(QtCore.QRect(570, 0, 21, 621))
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.line_45 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_45.setGeometry(QtCore.QRect(930, 0, 21, 621))
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.line_46 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_46.setGeometry(QtCore.QRect(540, 0, 2, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_46.sizePolicy().hasHeightForWidth())
        self.line_46.setSizePolicy(sizePolicy)
        self.line_46.setMinimumSize(QtCore.QSize(2, 0))
        self.line_46.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-color: rgb(125, 116, 255);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "\n"
                                   "border: 2px solid;")
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.line_47 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_47.setGeometry(QtCore.QRect(970, 0, 21, 621))
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.line_48 = QtWidgets.QFrame(self.gantaDiagramDataWidget)
        self.line_48.setGeometry(QtCore.QRect(810, -10, 21, 621))
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.line_41.raise_()
        self.line_44.raise_()
        self.line_40.raise_()
        self.line_45.raise_()
        self.line_48.raise_()
        self.line_43.raise_()
        self.line_46.raise_()
        self.line_39.raise_()
        self.line_38.raise_()
        self.line_47.raise_()
        self.line_37.raise_()
        self.line_42.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.verticalLayout.addWidget(self.gantaDiagramDataWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_32.setText(_translate("Form",
                                         "                                                                                            2024                                                                                                                                                     2025"))
        self.label_31.setText(_translate("Form",
                                         "                Янв       Фев       Март       Апр     Май      Июнь      Июль   Авг       Сен       Окт      Нояб     Дек       Янв       Фев       Март       Апр     Май      Июнь      Июль   Авг       Сен       Окт      Нояб     Дек"))
        self.label_4.setText(_translate("Form", "ВЫСТАВКА 1"))
        self.label_5.setText(_translate("Form", "ВЫСТАВКА 2"))
        self.label_6.setText(_translate("Form", "ВЫСТАВКА 3"))
        self.label_8.setText(_translate("Form", "ВЫСТАВКА 3"))
        self.label_10.setText(_translate("Form", "ВЫСТАВКА 4"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
