# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formActs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(924, 802)
        Dialog.setStyleSheet("QMenuBar {\n"
                             "background-color: rgb(250, 234, 153);\n"
                             "font: 87 10pt \"Arial Black\";\n"
                             "padding-left: 3px;\n"
                             "    color: rgb(82, 30, 1);\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item {\n"
                             "spacing: 3px; /* spacing between menu bar items */\n"
                             "padding: 1px 4px;\n"
                             "background: transparent;\n"
                             "border-radius: 4px;\n"
                             "background-color: rgb(250, 234, 153);\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
                             "background: #fac983;\n"
                             "}\n"
                             "\n"
                             "QMenu {\n"
                             "background-color: rgb(149, 166, 174); \n"
                             "    font: 75 8pt \"Arial Black\";\n"
                             "}\n"
                             "\n"
                             "QMenu::item {\n"
                             "background-color: transparent;\n"
                             "}\n"
                             "\n"
                             "QMenu::item:selected {\n"
                             "background-color: #fac983; /* rot */\n"
                             "}\n"
                             "QWidget{background-color: rgb(255, 253, 223);}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setStyleSheet("QCalendarWidget QWidget{\n"
                                          "    \n"
                                          "    font: 87 8pt \"Arial Black\";\n"
                                          "    color: #521e01;\n"
                                          "    background-color: #faebb4;\n"
                                          "}\n"
                                          "\n"
                                          "\n"
                                          "QCalendarWidget QAbstractItemView:enabled{\n"
                                          "background-color: #fffddf;\n"
                                          "font: 75 8pt \"Arial\";\n"
                                          "color: black;\n"
                                          "}")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setStyleSheet("border: 0px solid;\n"
                                      "QAbstractScrollArea {\n"
                                      "    \n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "\n"
                                      " QScrollBar::handle:vertical {\n"
                                      "    background: #fac983\n"
                                      " }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 450, 784))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginLabel_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel_2.sizePolicy().hasHeightForWidth())
        self.loginLabel_2.setSizePolicy(sizePolicy)
        self.loginLabel_2.setStyleSheet("QLabel {\n"
                                        "    font: 87 8pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}")
        self.loginLabel_2.setObjectName("loginLabel_2")
        self.verticalLayout.addWidget(self.loginLabel_2)
        self.loginLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.loginLineEdit.setEnabled(True)
        self.loginLineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit.setStyleSheet("QLineEdit {\n"
                                         "    \n"
                                         "    font: 8pt \"Arial\";\n"
                                         "    padding-left: 10px;\n"
                                         "    padding-right: 10px;\n"
                                         "    background-color: rgb(250, 235, 180);\n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:focus {\n"
                                         "  border: 2px solid rgb(250, 201, 131);\n"
                                         "}")
        self.loginLineEdit.setDragEnabled(True)
        self.loginLineEdit.setReadOnly(True)
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.verticalLayout.addWidget(self.loginLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel.sizePolicy().hasHeightForWidth())
        self.loginLabel.setSizePolicy(sizePolicy)
        self.loginLabel.setStyleSheet("QLabel {\n"
                                      "    font: 87 8pt \"Arial Black\";\n"
                                      "    color: rgb(82, 30, 1);\n"
                                      "}")
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_2.addWidget(self.loginLabel)
        self.loginLineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.loginLineEdit_2.setEnabled(True)
        self.loginLineEdit_2.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit_2.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit_2.setStyleSheet("QLineEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.loginLineEdit_2.setDragEnabled(True)
        self.loginLineEdit_2.setReadOnly(True)
        self.loginLineEdit_2.setObjectName("loginLineEdit_2")
        self.verticalLayout_2.addWidget(self.loginLineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
                                         "    \n"
                                         "    font: 8pt \"Arial Black\";\n"
                                         "    padding-left: 10px;\n"
                                         "    padding-right: 10px;\n"
                                         "    background-color: rgb(250, 235, 180);\n"
                                         "    border-radius: 10px;\n"
                                         "color: rgb(82, 30, 1);\n"
                                         "}\n"
                                         "\n"
                                         "QPlainTextEdit:focus {\n"
                                         "  border: 2px solid rgb(250, 201, 131);\n"
                                         "}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loginLabel_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel_3.sizePolicy().hasHeightForWidth())
        self.loginLabel_3.setSizePolicy(sizePolicy)
        self.loginLabel_3.setStyleSheet("QLabel {\n"
                                        "    font: 87 8pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}")
        self.loginLabel_3.setObjectName("loginLabel_3")
        self.verticalLayout_5.addWidget(self.loginLabel_3)
        self.loginLineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.loginLineEdit_3.setEnabled(True)
        self.loginLineEdit_3.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit_3.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit_3.setStyleSheet("QLineEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.loginLineEdit_3.setDragEnabled(True)
        self.loginLineEdit_3.setReadOnly(True)
        self.loginLineEdit_3.setObjectName("loginLineEdit_3")
        self.verticalLayout_5.addWidget(self.loginLineEdit_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.loginLabel_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel_4.sizePolicy().hasHeightForWidth())
        self.loginLabel_4.setSizePolicy(sizePolicy)
        self.loginLabel_4.setStyleSheet("QLabel {\n"
                                        "    font: 87 8pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}")
        self.loginLabel_4.setObjectName("loginLabel_4")
        self.verticalLayout_6.addWidget(self.loginLabel_4)
        self.loginLineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.loginLineEdit_4.setEnabled(True)
        self.loginLineEdit_4.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit_4.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit_4.setStyleSheet("QLineEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.loginLineEdit_4.setDragEnabled(True)
        self.loginLineEdit_4.setReadOnly(True)
        self.loginLineEdit_4.setObjectName("loginLineEdit_4")
        self.verticalLayout_6.addWidget(self.loginLineEdit_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial Black\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "color: rgb(82, 30, 1);\n"
                                           "}\n"
                                           "\n"
                                           "QPlainTextEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_4.addWidget(self.plainTextEdit_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.loginLabel_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel_5.sizePolicy().hasHeightForWidth())
        self.loginLabel_5.setSizePolicy(sizePolicy)
        self.loginLabel_5.setStyleSheet("QLabel {\n"
                                        "    font: 87 8pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}")
        self.loginLabel_5.setObjectName("loginLabel_5")
        self.verticalLayout_8.addWidget(self.loginLabel_5)
        self.loginLineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.loginLineEdit_5.setEnabled(True)
        self.loginLineEdit_5.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit_5.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit_5.setStyleSheet("QLineEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.loginLineEdit_5.setDragEnabled(True)
        self.loginLineEdit_5.setReadOnly(True)
        self.loginLineEdit_5.setObjectName("loginLineEdit_5")
        self.verticalLayout_8.addWidget(self.loginLineEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.loginLabel_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel_6.sizePolicy().hasHeightForWidth())
        self.loginLabel_6.setSizePolicy(sizePolicy)
        self.loginLabel_6.setStyleSheet("QLabel {\n"
                                        "    font: 87 8pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}")
        self.loginLabel_6.setObjectName("loginLabel_6")
        self.verticalLayout_9.addWidget(self.loginLabel_6)
        self.loginLineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.loginLineEdit_6.setEnabled(True)
        self.loginLineEdit_6.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit_6.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit_6.setStyleSheet("QLineEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "}\n"
                                           "\n"
                                           "QLineEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.loginLineEdit_6.setDragEnabled(True)
        self.loginLineEdit_6.setReadOnly(True)
        self.loginLineEdit_6.setObjectName("loginLineEdit_6")
        self.verticalLayout_9.addWidget(self.loginLineEdit_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit {\n"
                                           "    \n"
                                           "    font: 8pt \"Arial Black\";\n"
                                           "    padding-left: 10px;\n"
                                           "    padding-right: 10px;\n"
                                           "    background-color: rgb(250, 235, 180);\n"
                                           "    border-radius: 10px;\n"
                                           "color: rgb(82, 30, 1);\n"
                                           "}\n"
                                           "\n"
                                           "QPlainTextEdit:focus {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_7.addWidget(self.plainTextEdit_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginLabel_2.setText(_translate("Dialog", "Даритель"))
        self.loginLineEdit.setText(_translate("Dialog", "Иванов И.И."))
        self.loginLabel.setText(_translate("Dialog", "Дата подачи"))
        self.loginLineEdit_2.setText(_translate("Dialog", "20.12.2020"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "\n"
                                                             "\n"
                                                             "Фигурка льва, лежащего под деревом"))
        self.loginLabel_3.setText(_translate("Dialog", "Даритель"))
        self.loginLineEdit_3.setText(_translate("Dialog", "Иванов И.И."))
        self.loginLabel_4.setText(_translate("Dialog", "Дата подачи"))
        self.loginLineEdit_4.setText(_translate("Dialog", "20.12.2020"))
        self.plainTextEdit_2.setPlainText(_translate("Dialog", "\n"
                                                               "\n"
                                                               "Фигурка льва, лежащего под деревом"))
        self.loginLabel_5.setText(_translate("Dialog", "Даритель"))
        self.loginLineEdit_5.setText(_translate("Dialog", "Иванов И.И."))
        self.loginLabel_6.setText(_translate("Dialog", "Дата подачи"))
        self.loginLineEdit_6.setText(_translate("Dialog", "20.12.2020"))
        self.plainTextEdit_3.setPlainText(_translate("Dialog", "\n"
                                                               "\n"
                                                               "Фигурка льва, лежащего под деревом"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
