# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginScreenView(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.setWindowModality(QtCore.Qt.WindowModal)
        LoginScreen.resize(891, 0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginScreen.sizePolicy().hasHeightForWidth())
        LoginScreen.setSizePolicy(sizePolicy)
        LoginScreen.setMaximumSize(QtCore.QSize(1667777, 1667777))
        LoginScreen.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginScreen.setWindowIcon(icon)
        LoginScreen.setStyleSheet("background-color: rgb(255, 253, 223);")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginScreen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enterLayout = QtWidgets.QVBoxLayout()
        self.enterLayout.setObjectName("enterLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.enterLabel_3 = QtWidgets.QLabel(LoginScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterLabel_3.sizePolicy().hasHeightForWidth())
        self.enterLabel_3.setSizePolicy(sizePolicy)
        self.enterLabel_3.setMinimumSize(QtCore.QSize(190, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(10)
        self.enterLabel_3.setFont(font)
        self.enterLabel_3.setStyleSheet("QLabel {\n"
                                        "    font: 87 40pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}")
        self.enterLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.enterLabel_3.setObjectName("enterLabel_3")
        self.horizontalLayout_4.addWidget(self.enterLabel_3)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.enterLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.enterLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.appIcon = QtWidgets.QLabel(LoginScreen)
        self.appIcon.setText("")
        self.appIcon.setPixmap(QtGui.QPixmap("C:/Users/Telegrammer/Downloads/icon.png"))
        self.appIcon.setObjectName("appIcon")
        self.horizontalLayout_2.addWidget(self.appIcon)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.enterLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.enterLabel = QtWidgets.QLabel(LoginScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterLabel.sizePolicy().hasHeightForWidth())
        self.enterLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.enterLabel.setFont(font)
        self.enterLabel.setStyleSheet("QLabel {\n"
                                      "    font: 87 12pt \"Arial Black\";\n"
                                      "    color: rgb(82, 30, 1);\n"
                                      "}")
        self.enterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.enterLabel.setObjectName("enterLabel")
        self.horizontalLayout.addWidget(self.enterLabel)
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.enterLayout.addLayout(self.horizontalLayout)
        self.loginLabel = QtWidgets.QLabel(LoginScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginLabel.sizePolicy().hasHeightForWidth())
        self.loginLabel.setSizePolicy(sizePolicy)
        self.loginLabel.setStyleSheet("QLabel {\n"
                                      "    font: 87 8pt \"Arial Black\";\n"
                                      "    color: rgb(82, 30, 1);\n"
                                      "}")
        self.loginLabel.setObjectName("loginLabel")
        self.enterLayout.addWidget(self.loginLabel)
        self.loginLineEdit = QtWidgets.QLineEdit(LoginScreen)
        self.loginLineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.loginLineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.loginLineEdit.setStyleSheet("QLineEdit {\n"
                                         "    \n"
                                         "    font: 8pt \"Arial\";\n"
                                         "    padding-left: 10px;\n"
                                         "    padding-right: 10px;\n"
                                         "    background-color: rgb(250, 235, 180);\n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "\n"
                                         "QLineEdit:focus {\n"
                                         "  border: 2px solid rgb(250, 201, 131);\n"
                                         "}")
        self.loginLineEdit.setObjectName("loginLineEdit")
        self.enterLayout.addWidget(self.loginLineEdit)
        self.passwordLabel = QtWidgets.QLabel(LoginScreen)
        self.passwordLabel.setStyleSheet("QLabel {\n"
                                         "    font: 87 8pt \"Arial Black\";\n"
                                         "    color: rgb(82, 30, 1);\n"
                                         "}")
        self.passwordLabel.setObjectName("passwordLabel")
        self.enterLayout.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginScreen)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(0, 31))
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.passwordLineEdit.setStyleSheet("QLineEdit {\n"
                                            "    \n"
                                            "    font: 8pt \"Arial\";\n"
                                            "    padding-left: 10px;\n"
                                            "    padding-right: 10px;\n"
                                            "    background-color: rgb(250, 235, 180);\n"
                                            "    border-radius: 10px;\n"
                                            "}\n"
                                            "\n"
                                            "QLineEdit:focus {\n"
                                            "  border: 2px solid rgb(250, 201, 131);\n"
                                            "}")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.enterLayout.addWidget(self.passwordLineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.enterLayout.addItem(spacerItem7)
        self.logInButton = QtWidgets.QPushButton(LoginScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logInButton.sizePolicy().hasHeightForWidth())
        self.logInButton.setSizePolicy(sizePolicy)
        self.logInButton.setMinimumSize(QtCore.QSize(100, 31))
        self.logInButton.setMaximumSize(QtCore.QSize(16777215, 31))
        self.logInButton.setStyleSheet("QWidget {\n"
                                       "    background-color: rgb(250, 234, 153);\n"
                                       "    border: 1px solid rgb(250, 201, 131);\n"
                                       "    border-radius: 10px;\n"
                                       "    text-align: center;\n"
                                       "}\n"
                                       "\n"
                                       "QAbstractButton {\n"
                                       "    \n"
                                       "    font: 87 8pt \"Arial Black\";\n"
                                       "    color: rgb(82, 30, 1);\n"
                                       "}\n"
                                       "QPushButton:hover:!pressed {\n"
                                       "  border: 2px solid rgb(250, 201, 131);\n"
                                       "}")
        self.logInButton.setObjectName("logInButton")
        self.enterLayout.addWidget(self.logInButton)
        self.signInButton = QtWidgets.QPushButton(LoginScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signInButton.sizePolicy().hasHeightForWidth())
        self.signInButton.setSizePolicy(sizePolicy)
        self.signInButton.setMinimumSize(QtCore.QSize(100, 31))
        self.signInButton.setMaximumSize(QtCore.QSize(16777215, 31))
        self.signInButton.setStyleSheet("QWidget {\n"
                                        "    background-color: rgb(250, 234, 153);\n"
                                        "    border: 1px solid rgb(250, 201, 131);\n"
                                        "    border-radius: 10px;\n"
                                        "    text-align: center;\n"
                                        "}\n"
                                        "\n"
                                        "QAbstractButton {\n"
                                        "    font: 87 8pt \"Arial Black\";\n"
                                        "    color: rgb(82, 30, 1);\n"
                                        "}\n"
                                        "QPushButton:hover:!pressed {\n"
                                        "  border: 2px solid rgb(250, 201, 131);\n"
                                        "}")
        self.signInButton.setObjectName("signInButton")
        self.enterLayout.addWidget(self.signInButton)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.enterLayout.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.enterLayout)

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "Вход"))
        self.enterLabel_3.setText(_translate("LoginScreen", "МУЗЕЙ"))
        self.enterLabel.setText(_translate("LoginScreen", "Вход"))
        self.loginLabel.setText(_translate("LoginScreen", "Логин:"))
        self.passwordLabel.setText(_translate("LoginScreen", "Пароль:"))
        self.logInButton.setText(_translate("LoginScreen", "Войти"))
        self.signInButton.setText(_translate("LoginScreen", "Зарегестрироваться"))
        self.logInButton.setShortcut(_translate("LoginScreen", "Return"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoginScreen = QtWidgets.QWidget(None)
    ui = LoginScreenView()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
