# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'role_decision_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from src.SharedWidgets.MuseLabel import MuseLabel
from src.SharedWidgets.MuseButton import MuseButton


class RoleDecisionWidgetView(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(333, 106))
        Dialog.setMaximumSize(QtCore.QSize(333, 106))
        Dialog.setStyleSheet("QMenuBar {\n"
                             "background-color: rgb(250, 234, 153);\n"
                             "font: 87 10pt \"Arial Black\";\n"
                             "padding-left: 3px;\n"
                             "    color: rgb(82, 30, 1);\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item {\n"
                             "spacing: 3px; /* spacing between menu bar items */\n"
                             "padding: 1px 4px;\n"
                             "background: transparent;\n"
                             "border-radius: 4px;\n"
                             "background-color: rgb(250, 234, 153);\n"
                             "}\n"
                             "\n"
                             "QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
                             "background: #fac983;\n"
                             "}\n"
                             "\n"
                             "QMenu {\n"
                             "background-color: rgb(149, 166, 174); \n"
                             "    font: 75 8pt \"Arial Black\";\n"
                             "}\n"
                             "\n"
                             "QMenu::item {\n"
                             "background-color: transparent;\n"
                             "}\n"
                             "\n"
                             "QMenu::item:selected {\n"
                             "background-color: #fac983; /* rot */\n"
                             "}\n"
                             "QWidget{background-color: rgb(255, 253, 223);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = MuseLabel("Найдено несколько профилей с теми же данными", Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = MuseLabel("Выберете роль:", Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.donatorRoleButton = MuseButton("Даритель", Dialog)
        self.horizontalLayout.addWidget(self.donatorRoleButton)
        self.employeeRoleButton = MuseButton('Сотрудник', Dialog)
        self.horizontalLayout.addWidget(self.employeeRoleButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        QtCore.QMetaObject.connectSlotsByName(Dialog)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = RoleDecisionWidgetView()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
