# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from src.SharedWidgets.MuseLabel import MuseLabel

class Ui_formDialogWindow(object):
    def setupUi(self, formDialogWindow):
        formDialogWindow.setObjectName("formDialogWindow")
        formDialogWindow.resize(816, 642)
        formDialogWindow.setStyleSheet("QMenuBar {\n"
                                       "background-color: rgb(250, 234, 153);\n"
                                       "font: 87 10pt \"Arial Black\";\n"
                                       "padding-left: 3px;\n"
                                       "    color: rgb(82, 30, 1);\n"
                                       "}\n"
                                       "\n"
                                       "QMenuBar::item {\n"
                                       "spacing: 3px; /* spacing between menu bar items */\n"
                                       "padding: 1px 4px;\n"
                                       "background: transparent;\n"
                                       "border-radius: 4px;\n"
                                       "background-color: rgb(250, 234, 153);\n"
                                       "}\n"
                                       "\n"
                                       "QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
                                       "background: #fac983;\n"
                                       "}\n"
                                       "\n"
                                       "QMenu {\n"
                                       "background-color: rgb(149, 166, 174); \n"
                                       "    font: 75 8pt \"Arial Black\";\n"
                                       "}\n"
                                       "\n"
                                       "QMenu::item {\n"
                                       "background-color: transparent;\n"
                                       "}\n"
                                       "\n"
                                       "QMenu::item:selected {\n"
                                       "background-color: #fac983; /* rot */\n"
                                       "}\n"
                                       "QWidget{background-color: rgb(255, 253, 223);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(formDialogWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.headerLabel = MuseLabel("Поиск", formDialogWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerLabel.sizePolicy().hasHeightForWidth())
        self.headerLabel.setSizePolicy(sizePolicy)
        self.headerLabel.setStyleSheet("QLabel {\n"
                                       "    font: 87 15pt \"Arial Black\";\n"
                                       "    color: rgb(82, 30, 1);\n"
                                       "}")
        self.headerLabel.setObjectName("headerLabel")
        self.headerLayout.addWidget(self.headerLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.headerLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.availableFiltersLayout = QtWidgets.QHBoxLayout()
        self.availableFiltersLayout.setObjectName("availableFiltersLayout")
        self.filterLabel = MuseLabel("Доступные фильтры", formDialogWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterLabel.sizePolicy().hasHeightForWidth())
        self.filterLabel.setSizePolicy(sizePolicy)
        self.filterLabel.setStyleSheet("QLabel {\n"
                                       "    font: 87 10pt \"Arial Black\";\n"
                                       "    color: rgb(82, 30, 1);\n"
                                       "}")
        self.filterLabel.setObjectName("filterLabel")
        self.availableFiltersLayout.addWidget(self.filterLabel)
        self.filterComboBox = QtWidgets.QComboBox(formDialogWindow)
        self.filterComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.filterComboBox.setObjectName("filterComboBox")
        self.availableFiltersLayout.addWidget(self.filterComboBox)
        self.verticalLayout.addLayout(self.availableFiltersLayout)
        self.filterButtonsLayout = QtWidgets.QHBoxLayout()
        self.filterButtonsLayout.setObjectName("filterButtonsLayout")
        self.removeFilterButton = QtWidgets.QPushButton(formDialogWindow)
        self.removeFilterButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeFilterButton.sizePolicy().hasHeightForWidth())
        self.removeFilterButton.setSizePolicy(sizePolicy)
        self.removeFilterButton.setMinimumSize(QtCore.QSize(100, 31))
        self.removeFilterButton.setMaximumSize(QtCore.QSize(16777215, 31))
        self.removeFilterButton.setStyleSheet("QWidget {\n"
                                              "    background-color: rgb(250, 234, 153);\n"
                                              "    border: 1px solid rgb(250, 201, 131);\n"
                                              "    border-radius: 10px;\n"
                                              "    text-align: center;\n"
                                              "}\n"
                                              "\n"
                                              "QAbstractButton {\n"
                                              "    \n"
                                              "    font: 87 8pt \"Arial Black\";\n"
                                              "    color: rgb(82, 30, 1);\n"
                                              "}\n"
                                              "QPushButton:hover:!pressed {\n"
                                              "  border: 2px solid rgb(250, 201, 131);\n"
                                              "}")
        self.removeFilterButton.setObjectName("removeFilterButton")
        self.filterButtonsLayout.addWidget(self.removeFilterButton)
        self.addFilterButton = QtWidgets.QPushButton(formDialogWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFilterButton.sizePolicy().hasHeightForWidth())
        self.addFilterButton.setSizePolicy(sizePolicy)
        self.addFilterButton.setMinimumSize(QtCore.QSize(100, 31))
        self.addFilterButton.setMaximumSize(QtCore.QSize(16777215, 31))
        self.addFilterButton.setStyleSheet("QWidget {\n"
                                           "    background-color: rgb(250, 234, 153);\n"
                                           "    border: 1px solid rgb(250, 201, 131);\n"
                                           "    border-radius: 10px;\n"
                                           "    text-align: center;\n"
                                           "}\n"
                                           "\n"
                                           "QAbstractButton {\n"
                                           "    \n"
                                           "    font: 87 8pt \"Arial Black\";\n"
                                           "    color: rgb(82, 30, 1);\n"
                                           "}\n"
                                           "QPushButton:hover:!pressed {\n"
                                           "  border: 2px solid rgb(250, 201, 131);\n"
                                           "}")
        self.addFilterButton.setObjectName("addFilterButton")
        self.filterButtonsLayout.addWidget(self.addFilterButton)
        self.verticalLayout.addLayout(self.filterButtonsLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem2)
        self.filterDateRangeLayout = QtWidgets.QHBoxLayout()
        self.filterDateRangeLayout.setObjectName("filterDateRangeLayout")
        self.filterDateEditEnd = QtWidgets.QDateEdit(formDialogWindow)
        self.filterDateEditEnd.setMinimumSize(QtCore.QSize(0, 30))
        self.filterDateEditEnd.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
                                             "\n"
                                             "border: 1px solid;\n"
                                             "border-radius:  5px;\n"
                                             "")
        self.filterDateEditEnd.setObjectName("filterDateEditEnd")
        self.filterDateRangeLayout.addWidget(self.filterDateEditEnd)
        self.filterDateEditStart = QtWidgets.QDateEdit(formDialogWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterDateEditStart.sizePolicy().hasHeightForWidth())
        self.filterDateEditStart.setSizePolicy(sizePolicy)
        self.filterDateEditStart.setMinimumSize(QtCore.QSize(0, 30))
        self.filterDateEditStart.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
                                               "\n"
                                               "border: 1px solid;\n"
                                               "border-radius:  5px;\n"
                                               "")
        self.filterDateEditStart.setObjectName("filterDateEditStart")
        self.filterDateRangeLayout.addWidget(self.filterDateEditStart)
        self.verticalLayout.addLayout(self.filterDateRangeLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.dialogButtonsLayout = QtWidgets.QHBoxLayout()
        self.dialogButtonsLayout.setObjectName("dialogButtonsLayout")
        self.findConfirmButton = QtWidgets.QPushButton(formDialogWindow)
        self.findConfirmButton.setEnabled(True)
        self.findConfirmButton.setMinimumSize(QtCore.QSize(100, 31))
        self.findConfirmButton.setMaximumSize(QtCore.QSize(16777215, 31))
        self.findConfirmButton.setStyleSheet("QWidget {\n"
                                             "    background-color: rgb(250, 234, 153);\n"
                                             "    border: 1px solid rgb(250, 201, 131);\n"
                                             "    border-radius: 10px;\n"
                                             "    text-align: center;\n"
                                             "}\n"
                                             "\n"
                                             "QAbstractButton {\n"
                                             "    \n"
                                             "    font: 87 8pt \"Arial Black\";\n"
                                             "    color: rgb(82, 30, 1);\n"
                                             "}\n"
                                             "QPushButton:hover:!pressed {\n"
                                             "  border: 2px solid  rgb(250, 201, 131);\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "\n"
                                             "QPushButton:!enabled {\n"
                                             "    \n"
                                             "    background: rgba(160, 160, 160, 100);\n"
                                             "    font: 87 8pt \"Arial Black\";\n"
                                             "    border: 1px solid rgb(150, 150, 150);\n"
                                             "    border-radius: 10px;\n"
                                             "    color: rgba(82, 30, 1, 100);\n"
                                             "}")
        self.findConfirmButton.setObjectName("findConfirmButton")
        self.dialogButtonsLayout.addWidget(self.findConfirmButton)
        self.verticalLayout.addLayout(self.dialogButtonsLayout)

        self.retranslateUi(formDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(formDialogWindow)

    def retranslateUi(self, formDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        formDialogWindow.setWindowTitle(_translate("formDialogWindow", "Form"))
        self.headerLabel.setText(_translate("formDialogWindow", "ПОИСК"))
        self.filterLabel.setText(_translate("formDialogWindow", "Доступные фильтры"))
        self.removeFilterButton.setText(_translate("formDialogWindow", "Убрать фильтр"))
        self.removeFilterButton.setShortcut(_translate("formDialogWindow", "Ctrl+S"))
        self.addFilterButton.setText(_translate("formDialogWindow", "Добавить фильтр"))
        self.addFilterButton.setShortcut(_translate("formDialogWindow", "Ctrl+S"))
        self.findConfirmButton.setText(_translate("formDialogWindow", "Найти"))


if __name__ == "__main__":
    import sys


    app = QtWidgets.QApplication(sys.argv)
    formDialogWindow = QtWidgets.QWidget()
    ui = Ui_formDialogWindow()
    ui.setupUi(formDialogWindow)
    formDialogWindow.show()
    sys.exit(app.exec_())
